### ISSUE TITLE
Project doesn't compile after I include this library

### ISSUE THREAD

**Issue by ktmn** [roman01la/react-horizon#4] opened 2016-08-09 11:28 UTC
Hello!

If I do

`import { Horizon } from 'react-hz';`

I get

```
client:47 ./~/ws/lib/WebSocketServer.js
Module not found: Error: Cannot resolve module 'tls' in ...\node_modules\ws\lib
[...]
client:47 ./~/options/lib/options.js
Module not found: Error: Cannot resolve module 'fs' in ...\options\lib
[...]
```

so instead I do 

`import Horizon from '@horizon/client';`

and it's fine, I have a Horizon instance now.

Then I try for the provider:

`import { HorizonProvider } from 'react-hz';`

and I get the errors about missing 'tls' and 'fs' again.

My app is based on 'create-creact-app' and the 'horizon-react' library works well with it, so I wonder why this one doesn't.

**Comment by roman01la** [comment] 2016-08-25 11:03
@ktmn Hi. I think the problem is that internally I import dev build of `Horizon`. I'm not sure, but if you would like to fix this, I'll accept your PR. Thanks!

**Comment by tailsu** [comment] 2016-10-18 08:27
This problem is now fixed because react-hz doesn't depend explicitly on @horizon/client.

Installing @horizon/client@2.0.0 as a peer dependency fixes the problem.

**Comment by roman01la** [comment] 2016-10-18 08:32
Cool, thanks @tailsu

**Closed by roman01la** 2016-10-18 08:32 UTC
